function clone(value) {
  return value == null ? value : JSON.parse(JSON.stringify(value));
}

export function publicWorkflowSnapshot(runtime) {
  return {
    id: runtime.id,
    preset: runtime.config.preset || '',
    label: runtime.config.ux?.label || '',
    configPath: runtime.configPath,
    projectRoot: runtime.config.projectRoot,
    mode: runtime.config.watch.mode,
    status: String(runtime.workflowState?.watcher?.status || 'stopped'),
    sessionPolicy: runtime.config.automation?.session?.policy || 'current',
    pinnedSessionId: runtime.config.automation?.session?.id || '',
    restartPolicy: runtime.config.automation?.restartPolicy || 'ask',
    automationInterrupted: Boolean(runtime.automationInterrupted),
    clientId: runtime.config.watch.clientId,
    sessionId: runtime.config.watch.sessionId,
    watcher: clone(runtime.workflowState?.watcher || {}),
    pipeline: clone(runtime.workflowState?.pipeline || {}),
    automation: clone(runtime.workflowState?.automation || {}),
    workflowStateSchemaVersion: Number(runtime.workflowState?.schemaVersion || 0),
    lastOutcome: clone(runtime.workflowState?.lastOutcome || null),
    workflowStateRevision: Number(runtime.workflowState?.revision || 0),
    loadedAt: runtime.loadedAt,
    updatedAt: runtime.updatedAt,
    lastObservedTurnKey: runtime.lastObservedTurnKey,
    lastSourceClientId: runtime.lastSourceClientId,
    lastSessionId: runtime.lastSessionId,
    boundSourceClientId: runtime.boundSourceClientId,
    boundSessionId: runtime.boundSessionId,
    lastPipelineId: runtime.lastPipelineId,
    lastError: runtime.lastError,
    projectId: runtime.projectId || '',
    projectFingerprintSha256: runtime.projectFingerprintSha256 || '',
    contextSyncedSessionId: runtime.contextSyncedSessionId || '',
    contextSyncFingerprint: runtime.contextSyncFingerprint || '',
    workflowCommitBaseSha: runtime.workflowCommitBaseSha || '',
    workflowCommitShas: clone(runtime.workflowCommitShas || []),
    workflowCommitPaths: clone(runtime.workflowCommitPaths || []),
    workflowCommitPathStates: clone(runtime.workflowCommitPathStates || {}),
    lastWorkflowCommitMessage: runtime.lastWorkflowCommitMessage || '',
    pendingSessionRecovery: clone(runtime.pendingSessionRecovery || null),
    pendingCommit: clone(runtime.pendingCommit || null),
    pendingCheckFailure: clone(runtime.pendingCheckFailure || null),
    workflowTurnSessionId: runtime.workflowTurnSessionId || '',
    workflowTurnCount: Math.max(0, Number(runtime.workflowTurnCount) || 0),
    attention: clone(runtime.attention || null),
    ux: clone(runtime.config.ux || {}),
    resultProtocol: clone(runtime.config.resultProtocol || {}),
    intelligence: {
      model: String(runtime.config.ux?.intelligence?.model ?? runtime.config.automation?.turn?.model ?? ''),
      effort: String(runtime.config.ux?.intelligence?.effort ?? runtime.config.automation?.turn?.effort ?? ''),
    },
    checks: runtime.config.preset === 'apply-changes'
      ? clone(runtime.config.apply?.commands || [])
      : clone((runtime.config.automation?.steps || []).map((item) => item.command).filter(Boolean)),
    settings: {
      sessionExhaustion: runtime.config.ux?.sessionExhaustion || 'start-new-chat',
      session: clone(runtime.config.ux?.session || {}),
      invalidResponseAction: runtime.config.ux?.invalidResponseAction || 'repair',
      invalidResponseAttempts: Number(runtime.config.ux?.invalidResponseAttempts || 0),
      notifications: clone(runtime.config.ux?.notifications || {}),
      commits: clone(runtime.config.commit?.policy || {}),
      checks: {
        maxAttempts: Number(runtime.config.automation?.maxCycles || 8),
        noProgressLimit: Number(runtime.config.automation?.noProgressLimit || 3),
      },
    },
  };
}
