import crypto from 'node:crypto';
import fs from 'node:fs';
import path from 'node:path';

const ENV_FILE = process.env.ENV_FILE || '.env';

function loadDotEnv(filePath = ENV_FILE) {
  const absolutePath = path.resolve(filePath);
  if (!fs.existsSync(absolutePath)) return;

  const content = fs.readFileSync(absolutePath, 'utf8');
  for (const rawLine of content.split(/\r?\n/)) {
    const line = rawLine.trim();
    if (!line || line.startsWith('#')) continue;

    const index = line.indexOf('=');
    if (index === -1) continue;

    const key = line.slice(0, index).trim();
    if (!key || process.env[key] != null) continue;

    let value = line.slice(index + 1).trim();
    if ((value.startsWith('"') && value.endsWith('"')) || (value.startsWith("'") && value.endsWith("'"))) {
      value = value.slice(1, -1);
    }

    process.env[key] = value;
  }
}

function token() {
  return crypto.randomBytes(48).toString('base64url');
}

function envLine(key, value) {
  return `${key}=${String(value).replace(/\n/g, '')}`;
}

function ensureDotEnv(filePath = ENV_FILE) {
  const absolutePath = path.resolve(filePath);
  const generated = [];
  const defaults = {
    HOST: '127.0.0.1',
    PORT: '8080',
    API_TOKEN: token(),
    BRIDGE_TOKEN: token(),
  };

  if (process.env.PUBLIC_BASE_URL == null) {
    defaults.PUBLIC_BASE_URL = `http://${process.env.HOST || defaults.HOST}:${process.env.PORT || defaults.PORT}`;
  }

  let existing = '';
  try {
    existing = fs.existsSync(absolutePath) ? fs.readFileSync(absolutePath, 'utf8') : '';
  } catch {
    return { path: absolutePath, generated };
  }

  const existingKeys = new Set();
  for (const rawLine of existing.split(/\r?\n/)) {
    const line = rawLine.trim();
    if (!line || line.startsWith('#')) continue;
    const index = line.indexOf('=');
    if (index > 0) existingKeys.add(line.slice(0, index).trim());
  }

  const additions = [];
  for (const [key, value] of Object.entries(defaults)) {
    if (process.env[key] != null || existingKeys.has(key)) continue;
    additions.push(envLine(key, value));
    process.env[key] = value;
    generated.push(key);
  }

  if (!additions.length) return { path: absolutePath, generated };

  try {
    fs.mkdirSync(path.dirname(absolutePath), { recursive: true });
    const prefix = existing && !existing.endsWith('\n') ? '\n' : '';
    const header = existing ? '\n# Generated by chatgpt-browser-bridge setup\n' : '# Generated by chatgpt-browser-bridge setup\n';
    fs.writeFileSync(absolutePath, `${existing}${prefix}${header}${additions.join('\n')}\n`, 'utf8');
  } catch {
    // Keep generated values in process.env even if the file cannot be written.
  }

  return { path: absolutePath, generated };
}

loadDotEnv();
export const setupInfo = ensureDotEnv();
loadDotEnv();

function intFromEnv(name, fallback) {
  const raw = process.env[name];
  if (raw == null || raw === '') return fallback;

  const value = Number.parseInt(raw, 10);
  if (!Number.isFinite(value)) {
    throw new Error(`Invalid integer env ${name}: ${raw}`);
  }

  return value;
}

function boolFromEnv(name, fallback) {
  const raw = process.env[name];
  if (raw == null || raw === '') return fallback;
  return /^(1|true|yes|on)$/i.test(raw);
}

function csvFromEnv(name, fallback) {
  const raw = process.env[name];
  const source = raw == null || raw === '' ? fallback : raw;
  return String(source)
    .split(',')
    .map((item) => item.trim())
    .filter(Boolean);
}

export const config = Object.freeze({
  generatedEnv: setupInfo.generated,
  envFile: setupInfo.path,
  host: process.env.HOST || '127.0.0.1',
  port: intFromEnv('PORT', 8080),
  apiToken: process.env.API_TOKEN || '',
  activeClientId: process.env.ACTIVE_CLIENT_ID || '',
  payloadDebug: boolFromEnv('PAYLOAD_DEBUG', false),
  payloadDebugFile: path.resolve(process.env.PAYLOAD_DEBUG_FILE || './last_openclaw_payload.json'),
  jsonBodyLimit: process.env.JSON_BODY_LIMIT || '50mb',
  dataDir: path.resolve(process.env.DATA_DIR || './.bridge-data'),
  answerTimeoutMs: intFromEnv('ANSWER_TIMEOUT_MS', 120_000),
  answerSettleMs: intFromEnv('ANSWER_SETTLE_MS', 1500),
  answerDoneSettleMs: intFromEnv('ANSWER_DONE_SETTLE_MS', 600),
  promptAcceptedTimeoutMs: intFromEnv('PROMPT_ACCEPTED_TIMEOUT_MS', 10_000),
  heartbeatIntervalMs: intFromEnv('HEARTBEAT_INTERVAL_MS', 10_000),
  clientStaleMs: intFromEnv('CLIENT_STALE_MS', 30_000),
  tmPollTimeoutMs: intFromEnv('TM_POLL_TIMEOUT_MS', 25_000),
  tmCommandTimeoutMs: intFromEnv('TM_COMMAND_TIMEOUT_MS', 60_000),
  debugEventsLimit: intFromEnv('DEBUG_EVENTS_LIMIT', 250),
  bridgeToken: process.env.BRIDGE_TOKEN || '',
  publicBaseUrl: process.env.PUBLIC_BASE_URL || `http://${process.env.HOST || '127.0.0.1'}:${intFromEnv('PORT', 8080)}`,
  tmTransport: process.env.TM_TRANSPORT || 'polling',
  attachmentTransport: process.env.ATTACHMENT_TRANSPORT || 'url',
  artifactChunkTimeoutMs: intFromEnv('ARTIFACT_CHUNK_TIMEOUT_MS', 120_000),
  zipMaxEntries: intFromEnv('ZIP_MAX_ENTRIES', 5000),
  zipMaxUncompressedSize: intFromEnv('ZIP_MAX_UNCOMPRESSED_SIZE', 500 * 1024 * 1024),
  projectMaxFiles: intFromEnv('PROJECT_MAX_FILES', 2000),
  projectMaxZipBytes: intFromEnv('PROJECT_MAX_ZIP_BYTES', 50 * 1024 * 1024),
  projectMaxSingleFileBytes: intFromEnv('PROJECT_MAX_SINGLE_FILE_BYTES', 1024 * 1024),
  projectContextMaxSymbols: intFromEnv('PROJECT_CONTEXT_MAX_SYMBOLS', 2000),
  projectTreeLimit: intFromEnv('PROJECT_TREE_LIMIT', 500),
  allowedOrigins: csvFromEnv('ALLOWED_ORIGINS', 'https://chatgpt.com,https://chat.openai.com,null'),
});
